name: Continuous Integration and Pull Requests

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Push to master
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'

      - name: Check go version
        run: go version

      - name: Get dependencies
        run: |
          set GO111MODULE=on
          go get -d -v .\...

      - name: Run unit-tests
        run: go test -v .\...